import ilo
import time

ilo.check_robot_on_wifi()

my_ilo = ilo.robot(1)

my_ilo.set_led_shape('a')
time.sleep(2)
my_ilo.set_led_shape('b')
time.sleep(2)
my_ilo.set_led_shape('c')
time.sleep(2)
my_ilo.set_led_shape('d')
time.sleep(2)
my_ilo.set_led_shape('e')
time.sleep(2)
my_ilo.set_led_shape('f')
time.sleep(2)
my_ilo.set_led_shape('g')
time.sleep(2)
my_ilo.set_led_shape('h')
time.sleep(2)
my_ilo.set_led_shape('i')
time.sleep(2)
my_ilo.set_led_shape('j')
time.sleep(2)
my_ilo.set_led_shape('k')
time.sleep(2)
my_ilo.set_led_shape('l')
time.sleep(2)
my_ilo.set_led_shape('m')
time.sleep(2)
my_ilo.set_led_shape('n')
time.sleep(2)
my_ilo.set_led_shape('o')
time.sleep(2)
my_ilo.set_led_shape('p')
time.sleep(2)
my_ilo.set_led_shape('q')
time.sleep(2)
my_ilo.set_led_shape('r')
time.sleep(2)
my_ilo.set_led_shape('s')
time.sleep(2)
my_ilo.set_led_shape('t')
time.sleep(2)
my_ilo.set_led_shape('u')
time.sleep(2)
my_ilo.set_led_shape('v')
time.sleep(2)
my_ilo.set_led_shape('w')
time.sleep(2)
my_ilo.set_led_shape('x')
time.sleep(2)
my_ilo.set_led_shape('y')
time.sleep(2)
my_ilo.set_led_shape('z')
time.sleep(2)
