from ilo import info
from ilo import list_function
from ilo import connection
from ilo import stop
from ilo import test_connection
from ilo import step
from ilo import list_order
from ilo import move
from ilo import direct_control
from ilo import game
from ilo import get_color_clear
from ilo import get_color_clear_left
from ilo import get_color_clear_middle
from ilo import get_color_clear_right
from ilo import get_color_rgb
from ilo import get_distance
from ilo import get_angle
from ilo import reset_angle
from ilo import get_battery_info
from ilo import get_led_color
from ilo import set_led_color
from ilo import set_led_shape
from ilo import set_led_anim
from ilo import get_acceleration
from ilo import set_acceleration